// Generated by CoffeeScript 1.4.0

define(function(require, exports) {
  var codearea, get, paper;
  get = function(id) {
    return document.getElementById(id);
  };
  paper = get('paper');
  codearea = require('./codearea.coffee').codearea;
  codearea(paper);
  paper.focus();
});
